version: '3.9'

services:
  
  redis-fitnes:
    image: redis:7-alpine
    restart: always

  fitnes_io:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
      
  telegram-bot:
    build:
      context: ./telegram  # Path to the directory where your bot code (bot.py) resides
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=7866665708:AAHxg1medDESQqiPtJGOwTE-ZZ8utoPvyyI  # Your bot's token
    restart: always
    volumes:
      - ./telegram:/app  # Mount your local bot directory to allow live updates (optional)
    depends_on:
      - redis-fitnes  # Optional: If your bot needs to rely on other services like Redis

  db_fitnes:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=fitnes_io
      - POSTGRES_USER=fitnes_io_dev_user
      - POSTGRES_PASSWORD=fitnes_io_dev_user_password

volumes:
  postgres_data:
