version: '3.9'


services:
  
  redis-fitnes:
    image: redis:7-alpine
    restart: always

  fitnes_io:
    build: .
    command: python manage.py runserver 0.0.0.0:8010
    volumes:
      - .:/app
    ports:
      - 8010:8010
    depends_on:
      - db_fitnes
    
    # env_file:
    #   - .env
  
  # celery-worker:
  #   build: .
  #   command: celery -A Parking worker -l INFO
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis-fitnes:6379/0
    
  #   restart: always
  #   depends_on:
  #     - redis-fitnes

  db_fitnes:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=fitnes_io
      - POSTGRES_USER=fitnes_io_dev_user
      - POSTGRES_PASSWORD=fitnes_io_dev_user_password

volumes:
  postgres_data: