# Generated by Django 5.1.7 on 2025-04-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyexercisestranslation',
            name='name',
        ),
        migrations.AddField(
            model_name='dailyexercises',
            name='name',
            field=models.CharField(default='Exercise', max_length=100),
        ),
    ]
