# Generated by Django 5.2 on 2025-05-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyexercises',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
