# Generated by Django 5.1.7 on 2025-04-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_remove_dailyexercisestranslation_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyexercisestranslation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='routinetranslation',
            name='description',
        ),
        migrations.AddField(
            model_name='dailyexercises',
            name='description',
            field=models.TextField(default='Descrpition is not provided'),
        ),
        migrations.AddField(
            model_name='routine',
            name='description',
            field=models.TextField(default='Descrpition is not provided'),
        ),
    ]
