# Generated by Django 5.1.7 on 2025-04-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_remove_dailyexercisestranslation_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyfoodtranslation',
            name='description',
        ),
        migrations.AddField(
            model_name='dailyfood',
            name='description',
            field=models.TextField(default='Description is not provided'),
        ),
    ]
