"""
Django settings for fitnesIO project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--=k3ztr+xgx1ap5&a+@-grdk%p+fqe_itr_8+y@8no582!%e-8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'user',
    'googleauth',
    'routine',
    'utils',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fitnesIO.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fitnesIO.wsgi.application'
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis-fitnes:6379/1",  # Use DB 1 for caching
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get("SQL_ENGINE",'django.db.backends.postgresql'), 
        'NAME': os.environ.get("SQL_DATABASE",'new_fitnes'),
        'USER': os.environ.get("SQL_USER",'postgres_user'),
        'PASSWORD': os.environ.get("SQL_PASSWORD",'nitro'),
        'HOST': os.environ.get("SQL_HOST",'db_fitnes'),
        'PORT': os.environ.get("SQL_PORT",5432),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'user.CustomUser'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # SMTP Server configuration
EMAIL_HOST = 'smtp.gmail.com'  # Change to your provider's SMTP server
EMAIL_PORT = 587  # Use 465 for SSL
EMAIL_USE_TLS = True  # Set to False if you're using SSL
EMAIL_HOST_USER = 'mirjalolzokirov9.05@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'REMOVED_EMAIL_PASSWORD'  # Your email password or app password
EMAIL_HOST_NAME = 'FITNESSIO'
DEFAULT_FROM_EMAIL = f"FITNESSIO <{EMAIL_HOST_USER}>"

TWILIO_ACCOUNT_SID = 'REMOVED_TWILIO_SID'
TWILIO_AUTH_TOKEN = 'REMOVED_TWILIO_TOKEN'
TWILIO_PHONE_NUMBER = '+1 787 482 3824'

GOOGLE_CLIENT_ID = 'REMOVED_GOOGLE_CLIENT_ID'
GOOGLE_CLIENT_SECRET = 'REMOVED_GOOGLE_CLIENT_SECRET'
GOOGLE_REDIRECT_URI = 'http://localhost:8010/auth/google/callback/'
