"""
Django settings for fitnesIO project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
AUTH_USER_MODEL = 'user.CustomUser'
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--=k3ztr+xgx1ap5&a+@-grdk%p+fqe_itr_8+y@8no582!%e-8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'ai_model',
    'routine',
    'user',
    'utils',
    'parler',
    'drf_yasg',
    'myapp',
    'rest_framework.authtoken',
    'googleauth',
    'rest_framework_simplejwt',
    'telegram',
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny', # Default to requiring auth
    )
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # Access token expires in 30 minutes
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Refresh token expires in 7 days
    'ROTATE_REFRESH_TOKENS': True,                   # Issue a new refresh token on refresh
    'BLACKLIST_AFTER_ROTATION': True,                # Blacklist old refresh tokens         # Set a custom secret key if needed
    'AUTH_HEADER_TYPES': ('Bearer',),                # Default token type in headers
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'fitnesIO.urls'


CELERY_BROKER_URL = f'redis://redis-test:6379/0'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'default'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'fitnesIO.wsgi.application'
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis-fitnes:6379/1",  # Use DB 1 for caching
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

load_dotenv() 
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/chat/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

DATABASES = {
    'default': {
        'ENGINE': os.environ.get("SQL_ENGINE","django.db.backends.postgresql"),
        'NAME': os.environ.get("SQL_DATABASE","fitnes_io"),
        'USER': os.environ.get("SQL_USER","fitnes_io_dev_user"),
        'PASSWORD': os.environ.get("SQL_PASSWORD","fitnes_io_dev_user_password"),
        'HOST': os.environ.get("SQL_HOST","db_fitnes"),
        'PORT': os.environ.get("SQL_PORT","5432"),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'satic_root/'
STATIC_ROOT = 'satic_root/'

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR,'static')
# ]

MEDIA_URL = 'media/'
MEDIA_ROOT = 'media/'

AUTH_USER_MODEL = 'user.CustomUser'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # SMTP Server configuration
EMAIL_HOST = 'smtp.gmail.com'  # Change to your provider's SMTP server
EMAIL_PORT = 587  # Use 465 for SSL
EMAIL_USE_TLS = True  # Set to False if you're using SSL
EMAIL_HOST_USER = 'mirjalolzokirov9.05@gmail.com'  # Your email address
EMAIL_HOST_PASSWORD = 'REMOVED_EMAIL_PASSWORD'  # Your email password or app password
EMAIL_HOST_NAME = 'FITNESSIO'
DEFAULT_FROM_EMAIL = f"FITNESSIO <{EMAIL_HOST_USER}>"

TWILIO_ACCOUNT_SID = 'REMOVED_TWILIO_SID'
TWILIO_AUTH_TOKEN = 'REMOVED_TWILIO_TOKEN'
TWILIO_PHONE_NUMBER = '+1 787 482 3824'

GOOGLE_CLIENT_ID = 'REMOVED_GOOGLE_CLIENT_ID'
GOOGLE_CLIENT_SECRET = 'REMOVED_GOOGLE_CLIENT_SECRET'
GOOGLE_REDIRECT_URI = 'http://localhost:8010/auth/google/callback/'
